# prj.conf - Geral / Template
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3

# Console & Backend
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG_BACKEND_UART=y

# Melhora as mensagens de erro (Kernel Oops/Panic)
CONFIG_EXCEPTION_STACK_DUMP=y
CONFIG_ARCH_HAS_STACK_PROTECTION=y

# Facilita o uso de nomes em vez de IDs de thread no log
CONFIG_THREAD_NAME=y