# Log limpo para Windows
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BACKEND_SHOW_COLOR=n
CONFIG_LOG_BACKEND_UART=y

# Tempo real
CONFIG_QEMU_ICOUNT=y
CONFIG_QEMU_ICOUNT_SLEEP=y

# Console
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_MINIMAL_LIBC=y