# Habilita o sistema de logging do Zephyr
CONFIG_LOG=y
CONFIG_LOG_DEFAULT_LEVEL=3    # 0=none 1=err 2=wrn 3=inf 4=dbg

# Envia logs pro console (QEMU/serial)
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG_BACKEND_UART=y

# Opcional (não precisa pro LOG_INF, mas ajuda em outros prints)
CONFIG_PRINTK=y