CONFIG_LOG=y
# Se quiser comentar, faça na linha de CIMA, nunca na mesma linha
CONFIG_LOG_DEFAULT_LEVEL=3
CONFIG_LOG_MODE_IMMEDIATE=y
CONFIG_LOG_BACKEND_SHOW_COLOR=n

CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_STDOUT_CONSOLE=y

CONFIG_MINIMAL_LIBC=y
CONFIG_PICOLIBC=n

CONFIG_QEMU_ICOUNT=y
CONFIG_QEMU_ICOUNT_SLEEP=y